"""Vision-LLM-based PPTX review loop.

Pipeline:
    .pptx ─[pptx_to_png]─▶ slide-NN.png (one per slide)
                          │
                          ▼
                   per-slide vision-LLM call
                          │
                          ▼
                   structured JSON review
                          │
                          ▼
                   DeckReview aggregate

What the reviewer scores per slide:
    - typography (font choice, size hierarchy, readability)
    - palette (consistency with Praxia indigo/amber brand;
      avoidance of harsh black-on-white)
    - layout (whitespace, alignment, overflow, balance)
    - density (bullets count, chart legibility)
    - hierarchy (does the eye know where to start?)

Cost note:
    Vision-LLM calls are ~10-50x the cost of text-only calls.
    A 10-slide deck review with Claude Sonnet 4.6 runs about
    $0.10-0.50. The reviewer is opt-in via render_document's
    ``review=True`` parameter — defaulting to off keeps the
    common case cheap.
"""
from __future__ import annotations

import base64
import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from praxia.core.llm import LLM

_log = logging.getLogger(__name__)


_REVIEW_SYSTEM_PROMPT = """You are a presentation design reviewer.

You will be shown ONE slide image at a time from a PowerPoint deck
generated by an AI agent. The deck is intended to look like a
designed artefact, not a default-Office bullet list.

For each slide, evaluate FIVE dimensions on a 0-10 scale
(10 = excellent, 0 = broken):

  typography  Font choice and size hierarchy. Praxia uses Yu Gothic
              for Japanese and Segoe UI for English. Title >> body,
              not the same size. No Calibri / Times default fallbacks.
  palette     Color consistency. Praxia's brand is indigo (#1F3A8A
              primary) + amber (#F59E0B accent) on white/grey
              backgrounds. Flag harsh black on bright white, or
              random colours that don't match this palette.
  layout      Whitespace, alignment, balance. Flag text overflow,
              edges-touching elements, ragged left edges, charts
              squashed against bullets.
  density     Information density. 1 idea per slide. Cap at ~5
              bullets. Flag walls of text or 12-bullet slides.
  hierarchy   Where does the eye go first? Title should win, then
              the headline number / chart, then supporting body.

Output STRICT JSON:

{
  "slide_score": <0-10 overall>,
  "dimension_scores": {
    "typography": <0-10>,
    "palette":    <0-10>,
    "layout":     <0-10>,
    "density":    <0-10>,
    "hierarchy":  <0-10>
  },
  "issues": [
    {
      "category": "typography" | "palette" | "layout" | "density" | "hierarchy",
      "severity": "high" | "medium" | "low",
      "description": "<one concise sentence>",
      "suggested_fix": "<one concrete fix>"
    }
  ],
  "strengths": [ "<one sentence>", ... ]
}

Guidelines for issues:
  - "high"   = ships looking unprofessional. Always fix.
  - "medium" = a designer would change it. Fix when feasible.
  - "low"    = polish item. Nice-to-have.
Be specific in suggested_fix. "Change the title font" is bad;
"Use Segoe UI Semibold at 36pt instead of the default Calibri 28pt"
is what we want.
"""


@dataclass
class SlideReview:
    """Per-slide review result."""
    slide_number: int
    score: float                                  # 0-10
    dimension_scores: dict[str, float] = field(default_factory=dict)
    issues: list[dict[str, Any]] = field(default_factory=list)
    strengths: list[str] = field(default_factory=list)
    error: str = ""                               # populated on failure


@dataclass
class DeckReview:
    """Aggregate review across all slides."""
    slides: list[SlideReview]
    overall_score: float                          # mean of slide scores

    @property
    def high_severity_issues(self) -> list[dict[str, Any]]:
        """All issues marked severity=='high', with slide number injected."""
        out: list[dict[str, Any]] = []
        for sr in self.slides:
            for issue in sr.issues:
                if (issue.get("severity") or "").lower() == "high":
                    out.append({**issue, "slide": sr.slide_number})
        return out

    @property
    def summary(self) -> str:
        """Human-readable one-paragraph digest for the agent to return."""
        n_high = len(self.high_severity_issues)
        n_total = sum(len(sr.issues) for sr in self.slides)
        return (
            f"Overall score: {self.overall_score:.1f}/10 across "
            f"{len(self.slides)} slides. "
            f"{n_high} high-severity issue(s), {n_total} total."
        )

    def to_dict(self) -> dict[str, Any]:
        """Serialisable view suitable for embedding in a tool result."""
        return {
            "overall_score": round(self.overall_score, 2),
            "summary": self.summary,
            "slides": [
                {
                    "slide_number": sr.slide_number,
                    "score": round(sr.score, 2),
                    "dimension_scores": {
                        k: round(float(v), 2) for k, v in sr.dimension_scores.items()
                    },
                    "issues": sr.issues,
                    "strengths": sr.strengths,
                    **({"error": sr.error} if sr.error else {}),
                }
                for sr in self.slides
            ],
            "high_severity_issues": self.high_severity_issues,
        }


class PptxReviewer:
    """Renders each slide to PNG and asks a vision LLM to critique it.

    Args:
        llm: vision-capable LLM. The reviewer assumes the LLM accepts
            messages with image content blocks (OpenAI / Anthropic /
            Gemini-format multimodal). If the configured LLM doesn't
            support vision, the per-slide call surfaces the provider's
            error as ``SlideReview.error``.
        system_prompt: override the default critique instructions.
        max_response_tokens: cap per-slide JSON response. Default 1024
            is plenty for the JSON schema above.
    """

    def __init__(
        self,
        llm: "LLM",
        *,
        system_prompt: str = _REVIEW_SYSTEM_PROMPT,
        max_response_tokens: int = 1024,
    ) -> None:
        self.llm = llm
        self.system_prompt = system_prompt
        self.max_response_tokens = max_response_tokens

    def review(self, pptx_path: Path) -> DeckReview:
        """Run the full pipeline. Raises RuntimeError if PPTX rendering
        dependencies are missing; vision-LLM failures are captured
        per-slide in ``SlideReview.error`` rather than aborting."""
        from praxia.io.pptx_to_png import render_pptx_to_pngs
        png_paths = render_pptx_to_pngs(pptx_path)
        return self.review_pngs(png_paths)

    def review_pngs(self, png_paths: list[Path]) -> DeckReview:
        """Same as :meth:`review` but accepts pre-rendered PNGs. Used
        in tests and any caller that already has PNGs in hand."""
        slide_reviews: list[SlideReview] = []
        for i, png_path in enumerate(png_paths):
            slide_reviews.append(self._review_slide(png_path, slide_number=i + 1))
        if slide_reviews:
            overall = sum(sr.score for sr in slide_reviews) / len(slide_reviews)
        else:
            overall = 0.0
        return DeckReview(slides=slide_reviews, overall_score=overall)

    def _review_slide(self, png_path: Path, *, slide_number: int) -> SlideReview:
        try:
            png_bytes = png_path.read_bytes()
        except OSError as e:
            return SlideReview(
                slide_number=slide_number, score=0.0,
                error=f"Could not read PNG: {e}",
            )
        b64 = base64.b64encode(png_bytes).decode("ascii")
        messages = [
            {"role": "system", "content": self.system_prompt},
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": (
                            f"This is slide {slide_number}. "
                            "Review it per the rubric and reply with the "
                            "JSON shape exactly."
                        ),
                    },
                    {
                        "type": "image_url",
                        "image_url": {"url": f"data:image/png;base64,{b64}"},
                    },
                ],
            },
        ]
        try:
            resp = self.llm.complete(
                messages,
                max_tokens=self.max_response_tokens,
                response_format="json",
                temperature=0.0,
            )
        except Exception as e:
            _log.exception("Vision LLM call failed for slide %d", slide_number)
            return SlideReview(
                slide_number=slide_number, score=0.0,
                error=f"vision LLM call failed: {e}",
            )
        return self._build_review(resp.text, slide_number)

    @staticmethod
    def _build_review(raw_text: str, slide_number: int) -> SlideReview:
        parsed = _safe_parse_json(raw_text)
        return SlideReview(
            slide_number=slide_number,
            score=_safe_float(parsed.get("slide_score"), default=0.0),
            dimension_scores={
                k: _safe_float(v, default=0.0)
                for k, v in (parsed.get("dimension_scores") or {}).items()
            },
            issues=list(parsed.get("issues") or []),
            strengths=list(parsed.get("strengths") or []),
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _safe_parse_json(raw: str) -> dict[str, Any]:
    """Permissive JSON parser. Accepts a bare JSON object, or a code
    fence with JSON inside, or text that contains one ``{...}`` block.
    Returns ``{}`` if nothing usable parses — the caller assigns a
    zero score in that case."""
    if not raw:
        return {}
    s = raw.strip()
    # Strip ```json ... ``` fences if present
    if s.startswith("```"):
        first_nl = s.find("\n")
        if first_nl > 0:
            s = s[first_nl + 1 :]
        if s.endswith("```"):
            s = s[:-3]
        s = s.strip()
    try:
        obj = json.loads(s)
        return obj if isinstance(obj, dict) else {}
    except Exception:
        pass
    # Last resort: lift the first {...} block.
    start = s.find("{")
    end = s.rfind("}")
    if 0 <= start < end:
        try:
            obj = json.loads(s[start : end + 1])
            return obj if isinstance(obj, dict) else {}
        except Exception:
            return {}
    return {}


def _safe_float(value: Any, *, default: float = 0.0) -> float:
    if value is None:
        return default
    try:
        return float(value)
    except (TypeError, ValueError):
        return default
